fc_dca:
    local_dataset:
        data: test.csv
        task: denoising
        target_value: gene counts
        loginput: True
        norminput: True
        transpose: True
    model_parameters:
        epoch: 500
        lr: 0.001
        batch: 32
        encoder_size: 64
        bottleneck_size: 32
        ridge: 0.0
        reduce_lr: 20
        early_stopping: 25
        name: dca
        seed: 42
        param_factor: 1
        model_type: zinb #or nb
    result: 
        data: mean.csv
        denoise: True