fc_dca:
    local_dataset:
        data: test.csv
        loginput: True
        norminput: True
        transpose: True
        test_split: True
        filter_min_counts: True
        size_factor: True
    model_parameters:
        epoch: 250
        lr: 0.001
        batch: 32
        encoder_size: 64
        bottleneck_size: 32
        ridge: 0.0
        reduce_lr: 10
        early_stopping: 15
        name: dca
        seed: 42
        param_factor: 1
        model_type: zinb #or nb
    result: 
        data: mean.csv
        denoise: True